### PR TITLE
Modularize nndownload

### PR DESCRIPTION
**Pull request by jaeseopark**
Converted `nndownload` into a python module.

The standalone mode continues to work as it currently does. no changes there.

It's probably very hard to see what parts of the code changed, because diff in Git is all red and green. [Here](https://github.com/jaeseopark/nndownload/commit/354e757a5e914fd64df5094e5dc1371edf5bac0c) is a better view of what has changed exactly.

summary:
1. changed how `logger` is initialized and used. This is to allow `nndownload` to inherit any log configurations from the caller-module.
1. `main()` no longer calls `sys.exit()` when an exception is thrown. Instead, it simply bubbles the exception up, so the `except` block of the caller-module can do the rest.

I put the pypi badge in the README but haven't actually uploaded the package to pypi. It's on [TestPyPi](https://test.pypi.org/project/nndownload/), though.

### CODE REVIEW

**Comment by AlexAplin** [comment]
- Logging and quiet flags no longer controlled by the module. These should always be available, so I've changed how the logger behaves.
- Moved `__main__` back into the main script.
- Changed module function to `execute()` since it's basically a wrapper.

**Comment by AlexAplin** [comment]
@jaeseopark Please add me as the owner of the package (https://pypi.org/user/AlexAplin/).

**Comment by jaeseopark** [comment]
Thanks for the reminder. I added you. 

Do you know how to transfer the ownership entirely? I never intended to be an owner of this project.

**Comment by AlexAplin** [comment]
Thanks, I went ahead and removed you.

**Pull request merged**
